### ISSUE TITLE
TypeError: inner_function() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by arnydo** [kaisero/fireREST#28]
Good day,

Working on interfacing with our firewall and receiving the following error on some requests:

```
TypeError: inner_function() takes 1 positional argument but 2 were given
```

An example is:
```
...
>>> api.get_device_id_by_name('TESTFW')  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: inner_function() takes 1 positional argument but 2 were given
```

As well as:
```
>>> api.get_accesspolicy_id_by_name('test-policy')   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: inner_function() takes 1 positional argument but 2 were given
```

## Info
Python: 3.7.3
FMC: 6.6.0.1
fireREST: 0.1.4

**Comment by kaisero** [comment]
Fixed in v0.1.5
