### ISSUE TITLE
simplejson.errors.JSONDecodeError after FMC initialization

### ISSUE THREAD

**Issue by AlexanderTyutin** [kaisero/fireREST#37]
Hello! Any help is greatly appreciated with this issue.

During initialization I'm receiving this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/fireREST/__init__.py", line 42, in __init__
    self.conn = Connection(hostname, username, password, protocol, verify_cert, domain, timeout)
  File "/usr/local/lib/python3.8/dist-packages/fireREST/fmc/__init__.py", line 69, in __init__
    self.login()
  File "/usr/local/lib/python3.8/dist-packages/fireREST/fmc/__init__.py", line 203, in login
    response = self._request('post', url, auth=self.cred)
  File "<decorator-gen-2>", line 2, in wrapper
  File "/usr/local/lib/python3.8/dist-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/usr/local/lib/python3.8/dist-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.8/dist-packages/fireREST/utils.py", line 189, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fireREST/fmc/__init__.py", line 112, in _request
    logger.debug('\n"response": %s', json.dumps(response.json(), sort_keys=True, indent=4))
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Step to reproduce:
1. Run the command
```
fmc = FMC(hostname=FMC_HOST, username=FMC_USER, password=FMC_PASS, domain='Global')
```

Environment:
* 20.04.1 LTS (Focal Fossa)
* python 3.8.5
* Cisco Firepower Management Center for KVM, Software Version 6.4.0.6 (build 28)

Additional information:
* As I see the authentication was successful (my session in web browser was closed after I ran the command).
* No errors in Cisco Firepower logs.

**Comment by kaisero** [comment]
It looks like the error is caused by Ubuntu having simplejson module installed. The requests library automatically used simplejson instead of the builtin json library causing the exception handling to fail. I adressed the issue in v.1.0.1, can you try updating via pip and trying again?
