### ISSUE TITLE
policy.ftdnatpolicy.natrule.get passes expanded parameter when it shouldn't, or I'm doing it wrong.

### ISSUE THREAD

**Issue by tehsuk** [kaisero/fireREST#43]
I have a NAT policy with 2 rules.  I'm able to return a list of both rules with:

```python
fmc.policy.ftdnatpolicy.natrule.get(container_name='Test Threat Defense NAT', data={})
```

or 

```python
fmc.policy.ftdnatpolicy.natrule.get(container_name='Test Threat Defense NAT', data=None)
```

What I'm not able to do is get a specific rule by id.  I've tried:

```python
fmc.policy.ftdnatpolicy.natrule.get(container_name='Test Threat Defense NAT', uuid='005056B9-24B2-0ed3-0000-008589936189', data={})
```

and

```python
fmc.policy.ftdnatpolicy.natrule.get(container_name='Test Threat Defense NAT', uuid='005056B9-24B2-0ed3-0000-008589936189', data=None)
```

and the following error is returned:

```
Traceback (most recent call last):
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/utils.py", line 190, in wrapper
    response.raise_for_status()
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: 400 for url: https://fmc/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/ftdnatpolicies/005056B9-24B2-0ed3-0000-008589936073/natrules/005056B9-24B2-0ed3-0000-008589936189?limit=1000&expanded=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/utils.py", line 170, in wrapper
    return f(*args, **kwargs)
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/fmc/policy/ftdnatpolicy/natrule/__init__.py", line 50, in get
    container_uuid=container_uuid, container_name=container_name, name=name, uuid=uuid, params=params
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/utils.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/utils.py", line 78, in wrapper
    return f(*args, **kwargs)
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/fmc/__init__.py", line 430, in get
    return self.conn.get(url, params)
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/fmc/__init__.py", line 140, in get
    response = self._request('get', url, params=params)
  File "<decorator-gen-2>", line 2, in wrapper
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/utils.py", line 196, in wrapper
    raise_for_status(response)
  File "/path/to/.pyenv/versions/venv/lib/python3.7/site-packages/fireREST/utils.py", line 239, in raise_for_status
    raise exceptions.get(status_code, HTTPError)(msg=response.json()['error']['messages'][0]['description'])
fireREST.exceptions.GenericApiError: Invalid query parameter for the GETBYID operation.
```

I'm able to get it with a filter:

```python
fmc.policy.ftdnatpolicy.natrule.get(container_name='Test Threat Defense NAT', translated_source='10.117.108.194-32', data=None)
```

```python
[{'metadata': {'section': 'BEFORE_AUTO', 'index': 1, 'parentType': 'FTDNatRule', 'timestamp': 1612906807140, 'domain': {'name': 'Global', 'id': 'e276abec-e0f2-11e3-8169-6d9ed49b625f', 'type': 'Domain'}}, 'links': {'self': 'https://fmc/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/ftdnatpolicies/005056B9-24B2-0ed3-0000-008589936073/manualnatrules/005056B9-24B2-0ed3-0000-008589936189', 'parent': 'https://fmc/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/ftdnatpolicies/005056B9-24B2-0ed3-0000-008589936073/natrules'}, 'enabled': True, 'unidirectional': False, 'translatedSource': {'type': 'Host', 'overridable': False, 'id': '005056B9-24B2-0ed3-0000-008589936145', 'name': '10.117.108.194-32'}, 'originalSource': {'type': 'Host', 'overridable': False, 'id': '005056B9-24B2-0ed3-0000-008589936145', 'name': '10.117.108.194-32'}, 'interfaceInOriginalDestination': False, 'interfaceInTranslatedSource': False, 'type': 'FTDManualNatRule', 'fallThrough': False, 'dns': True, 'routeLookup': False, 'noProxyArp': False, 'netToNet': False, 'natType': 'STATIC', 'interfaceIpv6': False, 'id': '005056B9-24B2-0ed3-0000-008589936189'}]
```

2 questions:

- How would I query for a specific NAT rule by ID?
- Why is data marked as a required parameter?  The GET methods for `/api/fmc_config/v1/domain/{domainUUID}/policy/ftdnatpolicies/{containerUUID}/natrules` and `/api/fmc_config/v1/domain/{domainUUID}/policy/ftdnatpolicies/{containerUUID}/natrules/{objectId}` don't support passing a body.

**Comment by kaisero** [comment]
data field should not be required for GET operations, that is definetely a bug. I'll create a fix and look into the GET_BY_ID issue as well. In theory you should be able to call `fmc.policy.ftdnatpolicy.natrule.get(container_uuid=UUID-OF-NAT-POLICY, uuid=UUID-OF-NAT-RULE)`

**Comment by kaisero** [comment]
I tested your issue in my lab and found that there were two issues occuring. The first issue was that there was a bug in FireREST that caused the lookup by container_name to fail if a GET_BY_ID operation was performed. I fixed it and also fixed another issue with the error handling not displaying exactly why the GET_BY_ID call for the natrule is not working correctly.

The reason is that GET_BY_ID is not supported for natrules by FMC API (6.7.0). I will push a new release today that will fix the FireREST issues, however I think you can achieve what you want to do using the autonatrule or manualnatrule resources which support GET_BY_ID operations
