### ISSUE TITLE
Unable to pull application category by id

### ISSUE THREAD

**Issue by netman2048** [kaisero/fireREST#59]
I'm trying to extract the applications from a access rule and if you have a rule that references an app category, the information returned by the API is not helpful unless you make a second call to pull the app category by the ID returned by the first API call.  When I use the fmc.object.applicationcategory(uuid={'some_id'}) call, it fails with an HTTP 400 client error.  I'll provide the trace below.

For example, I have an inline application filter of type 'categories' in a rule.  The rule really references the 'database' category, but the API returns:

```
{'id': '32', 'name': 'category', 'type': 'ApplicationCategory'}
```

If I use the API explorer to pull this, it works perfectly.  The API explorer uses this as the URL:

```
https://x.x.x.x/api/fmc_config/v1/domain/{fmc_uuid}/object/applicationcategories/32
```

When I go to use fireREST, I get this traceback:

```
fmc.object.applicationcategory.get(uuid='32')
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\fireREST\utils.py", line 188, in wrapper
    response.raise_for_status()
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: 400 for url: https://x.x.x.x/api/fmc_config/v1/domain/{fmc_uuid}/object/applicationcategories/32?limit=1000&expanded=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\fireREST\utils.py", line 138, in wrapper
    return f(*args, **kwargs)
  File "C:\Python39\lib\site-packages\fireREST\utils.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "C:\Python39\lib\site-packages\fireREST\fmc\__init__.py", line 372, in get
    return self.conn.get(url, params)
  File "C:\Python39\lib\site-packages\fireREST\fmc\__init__.py", line 165, in get
    response = self._request('get', url, params=params)
  File "C:\Python39\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Python39\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "C:\Python39\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Python39\lib\site-packages\fireREST\utils.py", line 198, in wrapper
    raise_for_status(response)
  File "C:\Python39\lib\site-packages\fireREST\utils.py", line 246, in raise_for_status
    raise exceptions.get(status_code, exc.GenericApiError)(
fireREST.exceptions.GenericApiError: Invalid query parameter for the GETBYID operation.
```

Almost seems like it doesn't like the ```limit=1000&expanded=True``` part of the URL.

This was run on 6.7.0 code.

**Comment by kaisero** [comment]
There's a uuid check in utils.py that is used to check if a specific resource (get_by_id) is accessed. Unfortunetely applicationcategory objects do not use UUIDs but numeric IDs, hence the call fails. Fixed in v1.0.10
